<a href="https://colab.research.google.com/github/noahcurry1/it-262/blob/main/curryNoah_Pert_CPM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd 

simulationDF=pd.read_csv('/content/drive/MyDrive/IT262/PERTTestData-CPM.csv')
simulationDF.head(2)

,Unnamed: 0,A,B,C,D,E,F,G,H,I,J,EOP
0,0,6.914256,5.028610,2.900349,2.666650,7.671398,1.488743,4.067390,5.860282,14.768128,1.701084,NaN
1,1,7.276699,5.345718,2.982328,2.982551,6.051715,3.380045,8.554954,1.399733,14.631552,2.373477,NaN

In [9]:
paths=['ADEJ', 'BCDEJ', 'BCFGJ', 'BCFHJ', 'BI']
pathsDF=pd.DataFrame(columns=paths)
ADEJ=[]
BCDEJ=[]
BCFGJ=[]
BCFHJ=[]
BI=[]

for index, row in simulationDF.iterrows():
    ADEJ.append(row['A']+row['D']+row['E']+row['J'])
    BCDEJ.append(row['B']+row['C']+row['D']+row['E']+row['J'])
    BCFGJ.append(row['B']+row['C']+row['F']+row['G']+row['J'])
    BCFHJ.append(row['B']+row['C']+row['F']+row['H']+row['J'])
    BI.append(row['B']+row['I'])

pathsDF['ADEJ']=ADEJ
pathsDF['BCDEJ']=BCDEJ
pathsDF['BCFGJ']=BCFGJ
pathsDF['BCFHJ']=BCFHJ
pathsDF['BI']=BI
pathsDF.head(2)
#get max
pathsDF['critical']=pathsDF.idxmax(axis=1)
#print frequency 
print(pathsDF.critical.value_counts())

BCDEJ    3455
BCFGJ    2565
BI       2085
BCFHJ    1536
ADEJ      359
Name: critical, dtype: int64